[{assign var="payment" value=$oView->getPayment()}]
[{assign var="creditcardMode" value=$oView->getFatchipComputopShopCreditcardMode()}]

[{if $payment->oxpayments__oxid->value == 'fatchip_computop_creditcard' && $creditcardMode == 'SILENT'}]
    [{include file="fatchip_computop_creditcard_silentmode.tpl"}]
[{elseif $payment->oxpayments__oxid->value == 'fatchip_computop_amazonpay'}]
    [{include file="fatchip_computop_amazonpay.tpl"}]
[{else}]
    [{if $payment->oxpayments__oxid->value == 'fatchip_computop_ratepay_invoice' || $payment->oxpayments__oxid->value == 'fatchip_computop_ratepay_debit'}]
        [{oxid_include_dynamic file="fatchip_computop_ratepay.tpl" type="computop"}]
    [{/if}]
    [{$smarty.block.parent}]
[{/if}]
